import { signIn } from "next-auth/react";

import {
  Box,
  Button,
  Divider,
  Flex,
  Heading,
  HStack,
  SimpleGrid,
  VStack,
} from "@chakra-ui/react";

import { Input } from "../../components/Form/Input";

import { useForm } from "react-hook-form";

import Link from "next/link";
import { useRouter } from "next/router";
import { toast, ToastContainer } from "react-toastify";
import Head from "next/head";

interface Users {
  email: string;
  password: string;
}

export default function LoginAdmin() {
  const router = useRouter();

  const {
    register,
    handleSubmit,
    formState: { isSubmitting },
  } = useForm();

  async function handleSignIn(user: Users) {
    const result = await signIn("credentials", {
      redirect: false,
      email: user.email,
      password: user.password,
    });

    if (result.error) {
      toast.error("Invalid Username or Password");
    }

    if (result?.ok) {
      router.push("/");
    }
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <ToastContainer position="bottom-center" />

        <Flex w="100vw" h="100vh" align="center" justify="center">
          <Flex
            as="form"
            w="100%"
            maxWidth={360}
            bg="gray.800"
            p="8"
            borderRadius={8}
            flexDir="column"
            onSubmit={handleSubmit(handleSignIn)}
          >
            <Heading size="lg" fontWeight="normal">
              Login
            </Heading>

            <Divider my="6" borderColor="gray.700" />

            <VStack spacing="8">
              <SimpleGrid minChildWidth="240px" spacing={["6", "8"]} w="100%">
                <Input label="E-mail" type="email" {...register("email")} />
                <Input
                  label="Password"
                  type="password"
                  {...register("password")}
                />
              </SimpleGrid>
            </VStack>

            <Flex mt="8" justify="flex-end">
              <HStack spacing="4">
                <Link href="/" passHref legacyBehavior>
                  <Button as="a" colorScheme="whiteAlpha">
                    Cancel
                  </Button>
                </Link>
                <Button
                  type="submit"
                  colorScheme="pink"
                  isLoading={isSubmitting}
                >
                  Confirm
                </Button>
              </HStack>
            </Flex>
          </Flex>
        </Flex>
      </Box>
    </>
  );
}
