import {
  Box,
  Flex,
  Heading,
  Table,
  Tbody,
  Td,
  Text,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import Header from "../../../components/Header";

import Head from "next/head";

export default function Orders() {
  const [order, setOrder] = useState([]);

  useEffect(() => {
    async function loadOrders() {
      const orders = await fetch("/api/purchease/findOrder", {
        method: "GET",
      });

      const ordersJson = await orders.json();
      setOrder(ordersJson);
    }

    loadOrders();

    const orderProductId = order.map((order) => order.id);

    async function orderProduct(orderProductId) {
      const orderProduct = await fetch(
        `/api/products/findProduct?id=${orderProductId}`,
        {
          method: "GET",
        }
      );

      const orderProductJson = await orderProduct.json();
      setOrder(orderProductJson);
    }

    orderProduct(orderProductId);
    console.log(orderProductId);
  }, []);

  return (
    <>
      <Head>
        <title>My Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Header />
        <Flex w="100%" my="6" maxWidth={1480} mx="auto" px="6">
          <Box flex="1" borderRadius={8} bg="gray.800" p={["6", "8"]}>
            <Flex mb="8" justify="space-between" align="center">
              <Flex align="center" gap="8">
                <Heading size="lg" fontWeight="normal">
                  Orders
                </Heading>
              </Flex>
            </Flex>
            <>
              <Table colorScheme="whiteAlpha">
                <Thead>
                  <Tr>
                    <Th px={["4", "4", "6"]} color="gray.300" width="8"></Th>
                    <Th>Order</Th>
                    <Th>Total Price</Th>
                    <Th>Payment</Th>
                  </Tr>
                </Thead>

                <Tbody>
                  {order?.map((order) => (
                    <Tr key={order.id}>
                      <Td px={["4", "4", "6"]}>{}</Td>
                      <Td>
                        <Box>
                          <Text fontWeight="bold" color="purple.400">
                            {order.id}
                          </Text>
                        </Box>
                      </Td>
                      <Td>
                        <Box>
                          <Text fontWeight="bold" color="purple.400">
                            U$ {order.totalPrice}
                          </Text>
                        </Box>
                      </Td>
                      <Td>
                        <Box>
                          <Text fontWeight="bold" color="purple.400">
                            Paid
                          </Text>
                        </Box>
                      </Td>
                    </Tr>
                  ))}
                </Tbody>
              </Table>
            </>
          </Box>
        </Flex>
      </Box>
    </>
  );
}
