import {
  Box,
  Button,
  Card,
  Flex,
  Img,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import { toast, ToastContainer } from "react-toastify";
import Header from "../components/Header";
import { useCart } from "../hooks/useCart";
import { useProducts } from "../hooks/useProducts";

interface Product {
  id: number;
  description: string;
  name: string;
  price: number;
  image: string;
}

export default function Home() {
  const { data } = useProducts();
  const { addProduct } = useCart();

  function handleAddProduct(productId: number) {
    try {
      addProduct(productId);
    } catch (err) {
      toast.error(err.message);
    }

    toast.success("Added to Cart");
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" h="100vh">
        <ToastContainer position="bottom-center" />

        <Header />

        <Flex w="100%" my="6" maxWidth={1480} mx="auto" px="6">
          <Box
            flex="1"
            borderRadius={8}
            bg="gray.800"
            p={["6", "8"]}
            overflow="auto"
          >
            <SimpleGrid minChildWidth="320px" spacing="40px">
              {data?.map((product: Product) => (
                <Card
                  key={product.id}
                  p="6"
                  bg="gray.800"
                  borderRadius={8}
                  pb="4"
                  textColor="white"
                  align="center"
                  _hover={{
                    bg: "gray.700",
                  }}
                >
                  <Img
                    src={product.image}
                    alt={product.name}
                    mb="4"
                    borderRadius="full"
                    boxSize="150px"
                    mx="auto"
                  />

                  <Flex mb="4" justify="space-between" align="center">
                    <Flex direction="column">
                      <Text
                        fontWeight="bold"
                        fontSize="xl"
                        mb="2"
                        textAlign="center"
                        casing="capitalize"
                      >
                        {product.name}
                      </Text>
                      <Text
                        fontSize="sm"
                        textAlign="center"
                        casing="capitalize"
                      >
                        {product.description}
                      </Text>
                    </Flex>
                  </Flex>

                  <Flex justify="space-between" align="center">
                    <Button
                      onClick={() => handleAddProduct(product.id)}
                      colorScheme="pink"
                      textAlign="center"
                      _hover={{
                        bg: "pink.800",
                      }}
                    >
                      <strong>
                        {new Intl.NumberFormat("en-US", {
                          style: "currency",
                          currency: "USD",
                        }).format(product.price)}
                      </strong>
                    </Button>
                  </Flex>
                </Card>
              ))}
            </SimpleGrid>
          </Box>
        </Flex>
      </Flex>
    </>
  );
}
